name: Appsterdam Milan
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "pages/page:num"
timezone: Europe/Amsterdam
exclude: [LICENCE, README.md]
permalink: pages/:title/
embassy:
  name: Appsterdam Milan
  url: http://embassy.appsterdam.rs
  location: Milano
  email: info@appsterdam.rs
  social:
    twitter:
      handle: "@Appsterdam"
      url: https://twitter.com/AppsterdamMilan
    github:
      handle: Appsterdam
      url: https://www.github.com/appsterdam/open
    facebook: https://www.facebook.com/AppsterdamMilan
    linkedin: http://www.linkedin.com/groups/Appsterdam-3920468
    flickr: http://www.flickr.com/groups/1723974@N21
    youtube: http://www.youtube.com/appsterdam

